// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable
#pragma warning disable IDE0005 // Extra using directive is ok.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Agents.AI;
using Microsoft.Agents.AI.Workflows;
using Microsoft.Agents.AI.Workflows.Declarative;
using Microsoft.Agents.AI.Workflows.Declarative.Kit;
using Microsoft.Extensions.AI;

namespace Test.WorkflowProviders;

/// <summary>
/// This class provides a factory method to create a <see cref="Workflow" /> instance.
/// </summary>
/// <remarks>
/// The workflow defined here was generated from a declarative workflow definition.
/// Declarative workflows utilize Power FX for defining conditions and expressions.
/// To learn more about Power FX, see:
/// https://learn.microsoft.com/power-platform/power-fx/formula-reference-copilot-studio
/// </remarks>
public static class WorkflowProvider
{
    /// <summary>
    /// The root executor for a declarative workflow.
    /// </summary>
    internal sealed class MyWorkflowRootExecutor<TInput>(
        DeclarativeWorkflowOptions options,
        Func<TInput, ChatMessage> inputTransform) :
        RootExecutor<TInput>("my_workflow_Root", options, inputTransform)
        where TInput : notnull
    {
        protected override async ValueTask ExecuteAsync(TInput message, IWorkflowContext context, CancellationToken cancellationToken)
        {
            // Initialize variables
            await context.QueueStateUpdateAsync("TestInput", UnassignedValue.Instance, "Local").ConfigureAwait(false);
        }
    }
    
    /// <summary>
    /// Request input.
    /// </summary>
    internal sealed class QuestionInputExecutor(FormulaSession session) : ActionExecutor(id: "question_input", session)
    {
        // <inheritdoc />
        protected override async ValueTask<object?> ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)
        {
            await Task.Delay(0).ConfigureAwait(false);
    
            return default;
        }
    }
    
    public static Workflow CreateWorkflow<TInput>(
        DeclarativeWorkflowOptions options,
        Func<TInput, ChatMessage>? inputTransform = null) 
        where TInput : notnull
    {
        // Create root executor to initialize the workflow.
        inputTransform ??= (message) => DeclarativeWorkflowBuilder.DefaultTransform(message);
        MyWorkflowRootExecutor<TInput> myWorkflowRoot = new(options, inputTransform);
        DelegateExecutor myWorkflow = new(id: "my_workflow", myWorkflowRoot.Session);
        QuestionInputExecutor questionInput = new(myWorkflowRoot.Session);
        DelegateExecutor questionInputPost = new(id: "question_input_Post", myWorkflowRoot.Session);
        DelegateExecutor questionInputPrepare = new(id: "question_input_Prepare", myWorkflowRoot.Session);
        DelegateExecutor questionInputInput = new(id: "question_input_Input", myWorkflowRoot.Session);
        DelegateExecutor questionInputCapture = new(id: "question_input_Capture", myWorkflowRoot.Session);

        // Define the workflow builder
        WorkflowBuilder builder = new(myWorkflowRoot);

        // Connect executors
        builder.AddEdge(myWorkflowRoot, myWorkflow);
        builder.AddEdge(myWorkflow, questionInput);
        builder.AddEdge(questionInput, questionInputPost, (object? result) => !ActionExecutor.HasResult(result));
        builder.AddEdge(questionInput, questionInputPrepare, (object? result) => ActionExecutor.HasResult(result));
        builder.AddEdge(questionInputPrepare, questionInputInput);
        builder.AddEdge(questionInputInput, questionInputCapture);
        builder.AddEdge(questionInputCapture, questionInputPost, (object? result) => !ActionExecutor.HasResult(result));
        builder.AddEdge(questionInputCapture, questionInputPrepare, (object? result) => ActionExecutor.HasResult(result));

        // Build the workflow
        return builder.Build();
    }
}